In [39]:
import pandas as pd
import numpy as np
import tensorflow
import pickle
from sklearn.model_selection import train_test_split

In [40]:
data = pd.read_csv('Churn_Modelling.csv')
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [41]:
data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [42]:
## Convert categorical feature 'Gender' to numerical using saved label encoder

with open('label_encoder_gender.pkl', 'rb') as file:
    gender_encoder = pickle.load(file)

data['Gender'] = gender_encoder.transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [43]:
## Convert categorical feature 'Geography' to numerical using saved one hot encoder
with open('ohe_geo.pkl', 'rb') as file:
    geo_encoder = pickle.load(file)

## concatinate one hot encoded geography columns to the main dataframe
geo_encoded = geo_encoder.transform(data[['Geography']])
geo_df = pd.DataFrame(geo_encoded, columns=geo_encoder.get_feature_names_out(['Geography']))
data = pd.concat([data.drop('Geography', axis=1), geo_df], axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [47]:
X = data.drop(['EstimatedSalary', 'Exited'], axis=1)
y = data['EstimatedSalary']
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,1.0,0.0,0.0

In [48]:
# Split training data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [58]:
X_train.shape[1]

11

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [51]:
## Pickle the scaler for regression task
with open('scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [52]:
## Develop the ANN model for regression task
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [53]:
model = Sequential(
    [
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1)  # Single output neuron for regression
    ]
)

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

/Users/zarnanakrani/NLP/ANNClassification/venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [54]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,881 (11.25 KB)

 Trainable params: 2,881 (11.25 KB)

 Non-trainable params: 0 (0.00 B)

In [55]:
## Tensorboard setup

log_dir = "regressionlogs/fits/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [56]:
#Apply early stopping on the model

early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
history = model.fit(
    X_train, y_train,
    validation_data = (X_test, y_test),
    epochs=100,
    callbacks=[early_stopping, tensorboard_callback],
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 100426.1172 - mae: 100426.1172 - val_loss: 98707.5234 - val_mae: 98707.5234
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 100371.7422 - mae: 100371.7422 - val_loss: 98611.9141 - val_mae: 98611.9141
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 100197.7812 - mae: 100197.7812 - val_loss: 98349.9531 - val_mae: 98349.9531
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99760.7891 - mae: 99760.7891 - val_loss: 97768.6328 - val_mae: 97768.6328
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 98971.6797 - mae: 98971.6797 - val_loss: 96807.1016 - val_mae: 96807.1016
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 97795.4375 - mae: 97795.4375 - val_loss: 95469.4922 - val_mae: 95469.4922
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 96280.8672 - mae: 96280.8672 - val_loss: 93807.8594 - val_mae: 93807.8594
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 94501.4531 - mae: 94501.4531 - val_loss: 91891.9219 - val_mae: 91891.9219
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 92567.9375 - mae: 92567.9375 - val_loss: 89989.3750 - val_mae: 89989.3750
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 90738.5469 - mae: 90738.5469 - val_loss: 88362.3281 - val_mae: 88362.3281
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 89127.3516 - mae: 89127.3516 - val_loss: 86999.5859 - val_mae: 86999.5859
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 87755.7656 - mae: 87755.7656 - val_loss: 85943.8594 - val_mae: 85943.8594
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 86686.6250 - mae: 86686.6250 - val_loss: 85092.7656 - val_mae: 85092.7656
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 85894.0000 - mae: 85894.0000 - val_loss: 84431.7109 - val_mae: 84431.7109
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 85265.4531 - mae: 85265.4531 - val_loss: 83929.3125 - val_mae: 83929.3125
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84770.5234 - mae: 84770.5234 - val_loss: 83507.0312 - val_mae: 83507.0312
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 84404.3203 - mae: 84404.3203 - val_loss: 83152.1094 - val_mae: 83152.1094
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 84138.2812 - mae: 84138.2812 - val_loss: 82838.4844 - val_mae: 82838.4844
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 83879.5469 - mae: 83879.5469 - val_loss: 82573.5781 - val_mae: 82573.5781
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 83626.5391 - mae: 83626.5391 - val_loss: 82328.1172 - val_mae: 82328.1172
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83404.0938 - mae: 83404.0938 - val_loss: 82097.0469 - val_mae: 82097.0469
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 83201.3906 - mae: 83201.3906 - val_loss: 81873.7891 - val_mae: 81873.7891
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82986.3906 - mae: 82986.3906 - val_loss: 81665.8203 - val_mae: 81665.8203
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82796.8516 - mae: 82796.8516 - val_loss: 81463.7188 - val_mae: 81463.7188
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82572.5859 - mae: 82572.5859 - val_loss: 81272.6016 - val_mae: 81272.6016
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82418.8203 - mae: 82418.8203 - val_loss: 81100.3359 - val_mae: 81100.3359
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82216.9453 - mae: 82216.9453 - val_loss: 80935.8672 - val_mae: 80935.8672
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 82088.0000 - mae: 82088.0000 - val_loss: 80787.2422 - val_mae: 80787.2422
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 81937.6797 - mae: 81937.6797 - val_loss: 80660.3047 - val_mae: 80660.3047
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81814.6406 - mae: 81814.6406 - val_loss: 80514.6875 - val_mae: 80514.6875
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 81672.3516 - mae: 81672.3516 - val_loss: 80381.7266 - val_mae: 80381.7266
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81563.4688 - mae: 81563.4688 - val_loss: 80260.1172 - val_mae: 80260.1172
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 81447.5156 - mae: 81447.5156 - val_loss: 80125.3984 - val_mae: 80125.3984
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 81328.2188 - mae: 81328.2188 - val_loss: 80022.1328 - val_mae: 80022.1328
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 81162.1875 - mae: 81162.1875 - val_loss: 79869.2188 - val_mae: 79869.2188
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 81077.7344 - mae: 81077.7344 - val_loss: 79785.1562 - val_mae: 79785.1562
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80977.7109 - mae: 80977.7109 - val_loss: 79695.7031 - val_mae: 79695.7031
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80882.4844 - mae: 80882.4844 - val_loss: 79600.9141 - val_mae: 79600.9141
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80775.2422 - mae: 80775.2422 - val_loss: 79514.9609 - val_mae: 79514.9609
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80701.7734 - mae: 80701.7734 - val_loss: 79418.0859 - val_mae: 79418.0859
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80624.3516 - mae: 80624.3516 - val_loss: 79348.1094 - val_mae: 79348.1094
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80563.4219 - mae: 80563.4219 - val_loss: 79274.0703 - val_mae: 79274.0703
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80482.7734 - mae: 80482.7734 - val_loss: 79196.4766 - val_mae: 79196.4766
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80391.8984 - mae: 80391.8984 - val_loss: 79114.9922 - val_mae: 79114.9922
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80324.6953 - mae: 80324.6953 - val_loss: 79033.2812 - val_mae: 79033.2812
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80266.0156 - mae: 80266.0156 - val_loss: 78964.7266 - val_mae: 78964.7266
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80198.7031 - mae: 80198.7031 - val_loss: 78902.4922 - val_mae: 78902.4922
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80150.4766 - mae: 80150.4766 - val_loss: 78847.8281 - val_mae: 78847.8281
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80091.5234 - mae: 80091.5234 - val_loss: 78786.2344 - val_mae: 78786.2344
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 80010.6250 - mae: 80010.6250 - val_loss: 78705.0547 - val_mae: 78705.0547
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79957.1797 - mae: 79957.1797 - val_loss: 78666.2891 - val_mae: 78666.2891
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79924.9141 - mae: 79924.9141 - val_loss: 78624.1953 - val_mae: 78624.1953
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79881.7656 - mae: 79881.7656 - val_loss: 78574.5547 - val_mae: 78574.5547
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79842.2422 - mae: 79842.2422 - val_loss: 78539.2891 - val_mae: 78539.2891
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79811.2656 - mae: 79811.2656 - val_loss: 78493.7656 - val_mae: 78493.7656
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79767.6094 - mae: 79767.6094 - val_loss: 78454.2734 - val_mae: 78454.2734
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79723.9453 - mae: 79723.9453 - val_loss: 78436.5859 - val_mae: 78436.5859
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79701.1953 - mae: 79701.1953 - val_loss: 78398.1094 - val_mae: 78398.1094
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79666.6250 - mae: 79666.6250 - val_loss: 78348.5312 - val_mae: 78348.5312
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79640.5938 - mae: 79640.5938 - val_loss: 78305.3359 - val_mae: 78305.3359
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79599.5234 - mae: 79599.5234 - val_loss: 78263.7656 - val_mae: 78263.7656
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79551.1953 - mae: 79551.1953 - val_loss: 78208.5859 - val_mae: 78208.5859
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79492.8984 - mae: 79492.8984 - val_loss: 78162.9688 - val_mae: 78162.9688
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79465.9922 - mae: 79465.9922 - val_loss: 78139.6094 - val_mae: 78139.6094
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79426.5781 - mae: 79426.5781 - val_loss: 78113.2188 - val_mae: 78113.2188
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79399.5938 - mae: 79399.5938 - val_loss: 78083.8750 - val_mae: 78083.8750
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79372.2734 - mae: 79372.2734 - val_loss: 78055.4844 - val_mae: 78055.4844
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79329.6172 - mae: 79329.6172 - val_loss: 77982.0781 - val_mae: 77982.0781
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79290.4062 - mae: 79290.4062 - val_loss: 77947.5469 - val_mae: 77947.5469
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79239.5078 - mae: 79239.5078 - val_loss: 77922.0078 - val_mae: 77922.0078
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79217.4766 - mae: 79217.4766 - val_loss: 77884.0938 - val_mae: 77884.0938
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79177.9453 - mae: 79177.9453 - val_loss: 77864.0312 - val_mae: 77864.0312
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79167.4609 - mae: 79167.4609 - val_loss: 77826.4766 - val_mae: 77826.4766
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79128.3281 - mae: 79128.3281 - val_loss: 77825.0859 - val_mae: 77825.0859
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79113.2500 - mae: 79113.2500 - val_loss: 77785.5547 - val_mae: 77785.5547
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79081.7266 - mae: 79081.7266 - val_loss: 77726.5938 - val_mae: 77726.5938
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 79020.3906 - mae: 79020.3906 - val_loss: 77682.4531 - val_mae: 77682.4531
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78983.8984 - mae: 78983.8984 - val_loss: 77666.3750 - val_mae: 77666.3750
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78962.8281 - mae: 78962.8281 - val_loss: 77635.3594 - val_mae: 77635.3594
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78936.7266 - mae: 78936.7266 - val_loss: 77607.4141 - val_mae: 77607.4141
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78891.0156 - mae: 78891.0156 - val_loss: 77553.3672 - val_mae: 77553.3672
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78847.2812 - mae: 78847.2812 - val_loss: 77504.9531 - val_mae: 77504.9531
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78814.6172 - mae: 78814.6172 - val_loss: 77495.3438 - val_mae: 77495.3438
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78798.9766 - mae: 78798.9766 - val_loss: 77484.7734 - val_mae: 77484.7734
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78782.1797 - mae: 78782.1797 - val_loss: 77421.0469 - val_mae: 77421.0469
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78747.8828 - mae: 78747.8828 - val_loss: 77422.0469 - val_mae: 77422.0469
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78724.6016 - mae: 78724.6016 - val_loss: 77417.7812 - val_mae: 77417.7812
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78698.7812 - mae: 78698.7812 - val_loss: 77340.0078 - val_mae: 77340.0078
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78645.4922 - mae: 78645.4922 - val_loss: 77332.3672 - val_mae: 77332.3672
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78629.6172 - mae: 78629.6172 - val_loss: 77294.5781 - val_mae: 77294.5781
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78601.8281 - mae: 78601.8281 - val_loss: 77278.7656 - val_mae: 77278.7656
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78587.5547 - mae: 78587.5547 - val_loss: 77250.6797 - val_mae: 77250.6797
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78564.4219 - mae: 78564.4219 - val_loss: 77244.0469 - val_mae: 77244.0469
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 78540.9922 - mae: 78540.9922 - val_loss: 77195.7812 - val_mae: 77195.7812
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78519.4453 - mae: 78519.4453 - val_loss: 77190.8906 - val_mae: 77190.8906
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78503.1328 - mae: 78503.1328 - val_loss: 77164.5234 - val_mae: 77164.5234
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78481.8203 - mae: 78481.8203 - val_loss: 77132.1953 - val_mae: 77132.1953
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78451.1875 - mae: 78451.1875 - val_loss: 77123.2344 - val_mae: 77123.2344
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78414.3828 - mae: 78414.3828 - val_loss: 77079.7344 - val_mae: 77079.7344
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 78370.6875 - mae: 78370.6875 - val_loss: 77018.0234 - val_mae: 77018.0234

In [57]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fits

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 31527), started 1 day, 5:42:15 ago. (Use '!kill 31527' to kill it.)

In [60]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [61]:
test_loss, test_mae = model.evaluate(X_test, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 77018.0234 - mae: 77018.0234